---
# This playbook intends to install Openstack [Newton Branch]
# on a Ubuntu 16.04 server
#

- hosts: all
  vars:
    flavor_id: "{{ flavor_id }}"
    image_id: "{{ image_id }}"
    key_name: "{{ key_name }}"
    sec_group_name: "{{ sec_group_name }}"
    instance_name: "{{ instance_name }}"

  tasks:
  - name: Create Server Instance
    shell: openstack server create --flavor {{ flavor_id }} --image {{ image_id }}--key-name {{ key_name }} --user-data cloudinit.file --security-group {{ sec_group_name }} {{ instance_name }}
